### ISSUE TITLE
support for ironclust as input

### ISSUE THREAD

**Issue by WeissShahaf** [pynapple-org/pynapple#107]
Hi

what exactly is required to import data into pynapple? 
can you guys make a little doc on how to setup a new data importer? like the variables pynapple is looking for. how to format the data?
i'm trying to do it for ironclust and am a little lost.

**Comment by gviejo** [comment]
Hi Weiss, 

You can check this tutorial here : https://peyrachelab.github.io/pynapple/notebooks/pynapple-io-notebook/
