### ISSUE TITLE
Performance of compute_perievent

### ISSUE THREAD

**Issue by ahwillia** [pynapple-org/pynapple#114]
We are finding that `pynapple.compute_perievent` is a bit slow on some of our datasets that contain a very large number of neurons. I suspect (but have not confirmed) that we can make this go faster if we replaced the `align_to_event` function with something like the snippet below. The idea is that `np.searchsorted` is highly optimized and runs very fast if the `times` array is pre-sorted.

Would you be open to a PR for this? If so, I will do a more careful speed comparison. There are a few details that would need to be discussed, such as -- do you want to assume that the list of timestamps is maintained in sorted order. Also, it would be ideal if we could figure out a way to avoid the outer for loop over neurons and have this run all in one go. I think it should be possible.

```python
def align_to_event(times, data, tref, windowsize):
    """
    Helper function compiled with numba for aligning times.
    See compute_perievent for using this function

    Parameters
    ----------
    times : numpy.ndarray
        The timestamps to align, assumed to be sorted in ascending order
    data : numpy.ndarray
        The data to align
    tref : numpy.ndarray
        The reference times
    windowsize : tuple
        Start and end of the window size around tref

    Returns
    -------
    list
        The align times and data
    """
    lbounds = np.searchsorted(times, tref - windowsize[0])
    rbounds = np.searchsorted(times, tref + windowsize[1])
    x, y = [], []

    for tr, i0, i1 in zip(tref, lbounds, rbounds):
        x.append(times[i0:i1] - tr)
        y.append(data[i0:i1])

    return x, y
```

**Comment by gviejo** [comment]
Hey Alex, 
Thanks for testing it out. For sure, perievent is one of the slowest function so, it needs some boosting. I am currently rewriting most of the core functions to speed them up with numba jit. I will do the process functions after but feel free to open a PR. I hope to bump a new version with improved functions before Christmas so the new version of pynapple will hopefully be much faster.

Regarding your snippet,  you might want to test with and without the jit decorator. I found out that sometimes, when the function is full of high level numpy functions and you do a @jit(nopython=True), numba actually slows down a little bit the function. But if you manage to write the function with simple loops, it will probably be much faster. 
Also I agree that the outer for loop should be discarded. Numba has the option parallel=True if I remember correctly, and I wanted to test it for the high level functions. 

I am leaving the issue open until the function has been improved.

**Comment by ahwillia** [comment]
Thanks for letting me roll up my sleeves and get some coding done. I agree we should test with and without the `@jit` decorator.

Here is my thought for how you'd avoid the outer loop, but I need your feedback on whether this is the intended usage of your core classes. I'd start by having a single `Tsd` object where `index` is an array of spike times and `values` is an array of integer ids (e.g. the kilosort cluster id). Here is a code snippet to construct a synthetic data example:

```python
import numpy as np
import pynapple as nap
rs = np.random.RandomState(123)
num_neurons = 100
num_spikes = 10000
time_support = nap.IntervalSet(0, end=10, time_units="s")
unit_ids = rs.randint(num_neurons, size=num_spikes)
spike_times = np.sort(rs.uniform(
    time_support.start, time_support.end, num_spikes
))
full_spike_train = nap.Tsd(
    spike_times,
    d=unit_ids,
    time_units="s",
    time_support=time_support
)
```

Note that this is a distinct way of representing the multi-neuron spike train than is explained in the QuickStart with the `TsGroup` object. However, if we could quickly convert between the `TsGroup` representation and this alternative representation, I think we can do `compute_perievent` very fast. In particular, the following code snippet (similar to what I posted above) does the calculation:

```python
# K reference times for perievent windows.
tref = np.arange(1, 10)
windowsize = (-.2, .2)

# Array of spike times. Length = S.
times = full_spike_train.index

# Here is the bulk of the computation.
# Note that a call to numpy.searchsorted should take O( K * log S ) time.
lbounds = np.searchsorted(times, tref - windowsize[0])
rbounds = np.searchsorted(times, tref + windowsize[1])

# Now we collect the sub-series corresponding to trials.
trials = []
for tr, i0, i1 in zip(tref, lbounds, rbounds):
    trials.append(
        full_spike_train.iloc[i0:i1]
    )
    trials[-1].index -= tr
    # Also need to reset time_support here...
```

Testing this on my workstation, a call to `searchsorted` completes in a fraction of a second for a dataset with 100 million spikes and 10,000 trials. It completes in ~3 seconds for a dataset with 1 billion spikes. The bulk of computation time is now taken up in the final for loop over `zip(tref, lbounds, rbaounds)`.

What do you think of this approach?

**Comment by gviejo** [comment]
So I quickly tested this approach and I didn't get a better result at first with the quick code I wrote. I thought the bottleneck was the sorting of spikes times when converting from TsGroup to Tsd and back to TsGroup. 
But actually the bottleneck is instantiating a TsGroup for every neurons and every trials. If I remove the calling of TsGroup or Ts and just keep a dict of numpy array, the function goes from ~3 seconds to ~5 ms. 

I think this calls for me to keep rewriting the core functions right now.  I did not check in particular but I suspect it's the restrict function that is called in the __init__ to make sure all objects in the TsGroup are within the boundaries of the time support. I have a new optimized function for restrict so it should be faster for the next version. 

Apart from that, I also tested remplacing the jitted function align_to_event with a searchsorted function like you propose and it was 20 times faster so I am all in favor of this approach for the bulk of the perievent function.
If you want to do a pull request with a new version of perievent, please go ahead. I am still optimizing the core functions right now so there will be some time before I jump into the analysis functions.

**Comment by gviejo** [comment]
Hi Alex, 

I pushed the version 0.3 of pynapple hoping to solve some speed issues.
Have you tested it to see if it changes performances in your case?

**Comment by gviejo** [comment]
More optimization should come soon. Closing this.
