### ISSUE TITLE
Create a spike_index_array

### ISSUE THREAD

**Issue by apeyrache** [pynapple-org/pynapple#123]
A spike_index_array is tsd representing a "flatten" TsGroup in which data is the cell (or event) index.
Useful for plotting.

**Comment by gviejo** [comment]
What should be the name of that function?
tsgroup.raster()
tsgroup.to_tsd()
tsgroup.to_time_index()

**Comment by gviejo** [comment]
Ok 
And then reciprocally :
tsd.to_tsgroup()

**Comment by dlevenstein** [comment]
which would build a tsgroup with the times that correspond to each unique data value in the tsd? Do the values need to be integers?

**Comment by dlevenstein** [comment]
this could be useful for a lot of things actually :) e.g. if your Tsd has different classes of events and you want to group them into the timestamps of each event. cool

**Comment by gviejo** [comment]
I was gonna assume than yes. If not, the values will be converted to integers.

**Comment by dlevenstein** [comment]
how easy would it be to call pd.unique() to get the labels for the Tsgroup, then you don't need to assume integers

(though would probably call a warning or something if there's too many different values in the Tsd......)

**Comment by gviejo** [comment]
hum but that could turn it into a potentially huge TsGroup if all the elements are different.
Also TsGroup only accept integers as keys.

**Comment by dlevenstein** [comment]
integers it is

**Comment by gviejo** [comment]
Closing. This hsould appear in version 0.3.4
