### ISSUE TITLE
Incompatibility with `params` package because of parameters loading strategy

### ISSUE THREAD

**Issue by vigji** [pynapple-org/pynapple#134]
As defined in #132 , currently if the params library is installed the syntax in lines 85-90 of the `phy.py` loading module will fail. Parameters should be stored in a suitable file format (`.json` or `.yml`), that could also be used if we want to prevent the GUI to always open (#130).

**Comment by gviejo** [comment]
Closing this issue as phy will not be part of pynapple soon.
