### ISSUE TITLE
catching Tsdframe input when calling value_from

### ISSUE THREAD

**Issue by gviejo** [pynapple-org/pynapple#136]
throw error

**Comment by dlevenstein** [comment]
why error and not a Tsdframe containing the value of each column of the Tsdframe at the reference timestamps?

**Comment by gviejo** [comment]
Hum 🤔

**Comment by dlevenstein** [comment]
:D

**Comment by dlevenstein** [comment]
this is why you keep me around ;)

**Comment by gviejo** [comment]
Done in #139
