### ISSUE TITLE
LFP analysis

### ISSUE THREAD

**Issue by MKVarun** [pynapple-org/pynapple#163]
I am trying to perform LFP analysis for visual stimuli but am not able to find a function that performs this. Could anyone let me know if there is any function implemented in Pynapple?

**Comment by gviejo** [comment]
Hi what type of function are you looking for?

**Comment by MKVarun** [comment]
I was looking for functions like time-frequency analysis, power spectrum, phase amplitude coupling (PAC), or a voltage-time series plot averaged across trials on the LFP data.

**Comment by gviejo** [comment]
You just described the missing brick in the pynapple functions. It's in the roadmap so I will leave this issue open until it's resolved. If you have any code you think can be useful for it, please don't hesitate to open a PR.

**Comment by MKVarun** [comment]
Sure, that would be great to have these functions in the future! Thanks a lot!

**Comment by ckemere** [comment]
I'm trying to familiarize myself with Pynapple. I've done some basic analyses now with spikes and position data, and now I'm moving on to spectral analysis. I'm currently curious about whether you've already thought about how a spectrogram would be stored. Tsd objects have time as their abscissa, so it's easy enough to make a multidimensional Tsd, but I'd also like to store the axis data for the frequency dimension. Is there a pynapple object that has two dimensions?

Also - small plug for https://github.com/kemerelab/ghostipy, which can also be pip installed. Documentation isn't that great, but some of the desired functions are available.

**Comment by gviejo** [comment]
Hi Caleb, the object would be TsdFrame so time by frequency basically.

We are currently working on implementing some signal processing functions in pynapple. The most up to date pull request is #300.

Happy to receive some suggestions for it.

**Comment by gviejo** [comment]
Hello finally  pynapple 0.7.0 includes functions for signal processing. Check out those notebooks : 
https://pynapple.org/generated/api_guide/tutorial_pynapple_wavelets/
https://pynapple.org/generated/api_guide/tutorial_pynapple_filtering/
https://pynapple.org/generated/examples/tutorial_phase_preferences/
https://pynapple.org/generated/examples/tutorial_wavelet_decomposition/

Closing this issue.
