### ISSUE TITLE
Warning for interactive matplotlib

### ISSUE THREAD

**Issue by vigji** [pynapple-org/pynapple#179]
If I import pyneapple and try to use interactive matplotlib with `%matplotlib widget` I get the following working:

```
/.../miniconda3/envs/lab_env/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:477: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
NavigationToolbar2WebAgg.__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
```

This happens only if I import pynapple. This code does not raise the warning:

```python
%matplotlib widget
from matplotlib import pyplot as plt
plt.figure()
```

While this does:

```python
%matplotlib widget
from matplotlib import pyplot as plt
import pynapple as nap
plt.figure()
```

To see if it was coming from some dependency import, I tried to test the importing of all the requirements I read in the tool, but this does not produce the warning:

```python
%matplotlib widget
import pandas, numpy, scipy, numba, pynwb, tabulate, h5py, tifffile, zarr, rich
from matplotlib import pyplot as plt
plt.figure()
```

Have you ever seen this? Any pointers?

**Comment by gviejo** [comment]
Ok I can reproduce the error in a jupyter notebook. If I do `pip show traitlets`, it says 
```
Required-by: comm, ipykernel, ipympl, ipython, ipywidgets, jupyter-console, jupyter-events, jupyter_client, jupyter_core, jupyter_server, jupyterlab, matplotlib-inline, nbclient, nbconvert, nbformat, qtconsole
```

None of this is required by pynapple though so I am not sure what causes it.

**Comment by gviejo** [comment]
Hi can I close this? Is it still an issue?

**Comment by vigji** [comment]
I don't think it is super important, we can close it
