### ISSUE TITLE
Creating a lazy `TsdTensor`? 

### ISSUE THREAD

**Issue by kushalkolar** [pynapple-org/pynapple#185]
I was going through `TsdTensor` and I'm wondering if it supports lazy compute. 

Example use case:
With calcium imaging data, the outer product of spatial & temporal components can result in a huge array that is hundreds of gigabytes or terrabytes in size. It is almost never necessary to actually compute the entire array, so using a lazy compute data structure works well. The implementation in mescore computes the outer product only when the array is sliced: https://github.com/nel-lab/mesmerize-core/blob/master/mesmerize_core/arrays/_cnmf.py#L131-L141

**Comment by gviejo** [comment]
Hi Kushal it's a good idea but not sure in which case it could be used. Could you give an example of it?

**Comment by kushalkolar** [comment]
As discussed:

- So far, feeding a numpy memmap to `d` in `TsdTensor` seems to work.
- It's probably possible that any object that implements the numpy array API could work if fed to `d`. Will test with our `LazyArray` implementation, as well as other array types (like zarr, dask etc.)

**Comment by gviejo** [comment]
Merging it with #245
