### ISSUE TITLE
NWB file: adding group/naming information for LFPs/clusters

### ISSUE THREAD

**Issue by JohnStout** [pynapple-org/pynapple#187]
Was wondering if you could add electrode and unit names when running load_file() function with an NWB file.

I've added two screenshots, the first shows a DataFrame for the LFP signals, the second shows the group-name and labels of each LFP signal.

Thank you!

<img width="929" alt="Screenshot 2023-10-12 at 10 50 26 AM" src="https://github.com/pynapple-org/pynapple/assets/46092030/bd2af0af-cb60-48a9-a2df-73c53efe874b">

<img width="551" alt="Screenshot 2023-10-12 at 10 50 42 AM" src="https://github.com/pynapple-org/pynapple/assets/46092030/faff195f-efa8-430f-8665-256fe1905c1c">

**Comment by gviejo** [comment]
Hi John, I am not sure I understand. Do you want labelled columns when loading the LFP?

**Comment by JohnStout** [comment]
Hey Guillaume, yes exactly! I can reference back to the original file by like loading the raw nwbfile and aligning the nap ids with nwbfile ids, but I was wondering if I can just have pynapple group that information for me. So in that first screenshot, is there a way for index 0 to have an additional column or replacement column with 'CSC1', which is further grouped into 'Tetrode1' as shown in the second screenshot?

I'm working on a small package for the lab that uses pynapple and am looking for ways for users to index out information by entering the raw file name 'CSC1' or by entering grouped names like 'Tetrode1'.

I hope that my description is more clear this time

**Comment by gviejo** [comment]
Hi John, I think it's possible. If the nwb file has a label columns, it can be used as a column name for the TsdFrame. 
Also please note that I am about to bump the version 0.4 (next week) which relies on the numpy array container approach. This is different from inheriting pandas. You can install the pre-release version by doing `pip install --pre pynapple` to test it and make sure your code still works. You can also check this [notebook](https://pynapple-org.github.io/pynapple/generated/gallery/tutorial_pynapple_numpy/) to get an idea of how it works.

**Comment by JohnStout** [comment]
Okay I’ll check it out next week!

**Comment by gviejo** [comment]
Ok fixed. It's pushed to the main branch. It should appear in the next version soon.
