### ISSUE TITLE
Cannot find segmentation or iscell data for a neuroconv nwb file

### ISSUE THREAD

**Issue by msoheib** [pynapple-org/pynapple#215]
Hello

I used neuroconv to convert my suite2p data to nwb and as well the timestamps. Using nwbwidgets and neuro guide I can see the segmentation data, and, more importantly for me, the "iscell" results in the Accepted vs. Rejected columns of the Segmentation part of the nwb. Please see the picture attached below.

![accepted](https://github.com/pynapple-org/pynapple/assets/95087523/e3849e59-22c1-4ee2-a3cc-881aae5170da)

Upon loading the nwb file using nap.load_file() I am not able to see any segmentation file or ways to filter out the iscell from the roiresponseseries. See:

![nwb_h](https://github.com/pynapple-org/pynapple/assets/95087523/80288544-4a65-48fa-affb-c4c3b86cc8b9)

Am i doing something wrong here? Would appreciate any input on this matter.

Thank you.

**Comment by gviejo** [comment]
Hi, 
I don't think you are doing something wrong. Pynapple will load epochs and time series only. Segmentation files and labels are not time series so there is no corresponding pynapple objects. If the data were spike times, pynapple would have returned a `TsGroup` which can contains metainformation and would have tried to extract the labels such as good units vs bad units. There is no corresponding feature for now for regular time series. 
One solution for you is to extract manually the labels by going inside the open NWB file. To access the NWB file, you can look into `data.nwb`. 
From the screenshot you sent, it seems the path within the NWB will be something like this: `data.nwb.imaging_planes['ImagingPlane']`. From there you should be able to select the cells you want.

Extracting all the metainformation of a NWB file is not in the roadmap right now so I will close this issue.
If you have more questions, please consider joining the pynapple slack. There is a support channel. You can send us an email at thepynapple@gmail.com and we will send you an invitation link.
