### ISSUE TITLE
`TsGroup` cannot handle jax numpy arrays

### ISSUE THREAD

**Issue by billbrod** [pynapple-org/pynapple#221]
In general, pynapple objects seem to handle jax numpy arrays the same as numpy arrays, as expected. However, `TsGroup` is an exception:

```python
import numpy as np
import jax.numpy as jnp
import pynapple as nap

a = np.random.rand(100)
a.sort()
b = np.random.rand(100)

# these both work, as expected (as does analogous construction for TsdFrame, TsdTensor, Ts)
tsd = nap.Tsd(a, b)
jax_tsd = nap.Tsd(a, jnp.array(b))


tsg = nap.TsGroup({0: a})
# Fails with AttributeError: 'ArrayImpl' object has no attribute 'time_support'
jax_tsg = nap.TsGroup({0: jnp.array(a)})
```

I think this is because in the `__init__` of  `Tsgroup`, you explicitly check whether `data[k]` is either a `np.ndarray` or a `list`. Alternatively, you could check try to see whether it's array-like. Just checking whether you can cast it to an array won't work (`np.asarray({1: 'hi'})` succeeds, though you could try to specify a numeric dtype). You could also try to construct the `Ts` object that happens in that if statement and raise an exception if it fails.

**Comment by gviejo** [comment]
Now the behavior will be a conversion to numpy and a warning `UserWarning: Converting 'key 0' to numpy.array. The provided array was of type 'ArrayImpl'.`
Closing this thanks
