### ISSUE TITLE
concatenation of multidimensional arrays

### ISSUE THREAD

**Issue by BalzaniEdoardo** [pynapple-org/pynapple#222]
Hi all,
I have been trying to use the following syntax,
```python
import numpy as np
import pynapple as nap

time = np.arange(10)
X = nap.TsdTensor(t=time, d=np.zeros((10,1,1)))
Y = nap.TsdTensor(t=time, d=np.zeros((10,1,1)))
Z = np.concatenate([X, Y], 2)
```

In numpy that works, you can pass the axis as second argument, in pynapple I get a TypeError

```
TypeError: _concatenate_tsd() takes 2 positional arguments but 3 were given
```

This does not match the behavior of numpy.concatenate when pplied to arrays (`Z = np.concatenate([X.d, Y.d], 2)` works).

It would be nice if the behavior matched

**Comment by gviejo** [comment]
Hey this is not in the roadmap for now so I am going to close this issue.
