### ISSUE TITLE
Retrieving Ts object as array returns NoneType 

### ISSUE THREAD

**Issue by rcpeene** [pynapple-org/pynapple#229]
Can't seem to find a functional way to retrieve my Ts object as a numpy array. Using Pynapple 0.5.1

code:
```python
spike_train = units["spike_times"][0]
print(spike_train)
print("========")
tss = Ts(spike_train)
print(type(tss))
print(tss)
print("========")
print(type(tss.as_array()))
print(type(tss.data()))
print(type(tss.to_numpy()))
```

output:
```
[1.04394304e+00 1.54331106e+00 2.72878093e+00 ... 9.66379314e+03
 9.66475094e+03 9.66513561e+03]
========
<class 'pynapple.core.time_series.Ts'>
Time (s)
1.043943043
1.54331106
2.728780932
3.466616261
4.279985127
...
9663.558037293
9663.650970877
9663.793137928
9664.750940518
9665.135608225
shape: 38058
========
<class 'NoneType'>
<class 'NoneType'>
<class 'NoneType'>
```

**Comment by gviejo** [comment]
You have multiple choices: `tss.t` , `tss.index.values` or `tss.times()`.

The methods you used are for retrieving the data of a `Tsd`, `TsdFrame`, `TsdTensor` object.
A `Ts` object is for timestamps only.

If you have more questions about pynapple, please consider joining our slack. You can send me an email and I will send you an invitation link.

**Comment by rcpeene** [comment]
Ah thanks. I had been using https://pynapple-org.github.io/pynapple/reference/core/time_series/#pynapple.core.time_series.Ts this documentation, in which I can't seem to find those methods. The methods I used about show 
`Return the data as a numpy.ndarray. Mostly useful for matplotlib plotting when calling plot(tsd)` as descriptions. Perhaps could benefit from additional clarity.
