### ISSUE TITLE
Make `TsGroup` a Pandas `DataFrame`?

### ISSUE THREAD

**Issue by jsiegle** [pynapple-org/pynapple#246]
The `TsGroup` class behaves in many ways like a Pandas `DataFrame`. Given that a `DataFrame` is already being used under the hood to manage metadata for this class, it seems like making the whole thing into a `DataFrame` would be a natural choice.

Currently, there are a number of methods that are re-implemented in the `TsGroup` class that would come for free if it were a `DataFrame`:
- printing – Pandas has really nice printing methods, whereas the printout of a `TsGroup` is hard to read
- filtering – as mentioned in #243, the filtering syntax for a `TsGroup` is unnecessarily complex
- accessing columns – with a `DataFrame` I can simply call df.<column_name>, whereas `TsGroup` has reimplemented this as `get_info` (which ends up returning a Pandas `Series` object anyway)
- adding columns – adding a column to a `DataFrame` is done via bracket syntax, while `TsGroup` has a `set_info` method for this
- saving / loading – a `TsGroup` can only be saved as an .npz file and requires 4 lines of code to load, whereas Pandas supports a variety of file formats

There are of course many things (for example slicing or sorting) which can currently only be done with a `DataFrame`. And the unique methods of `TsGroup`, such as `restrict`, `value_from`, and `count`, would be straightforward to build on top of a `DataFrame`.

Therefore, my impression is that having `TsGroup` inherit from a `DataFrame` would reduce code complexity, make the class easier to interact with, and add substantial new functionality. Would the Pynapple devs consider doing this? If not, what are the reasons to avoid it?

**Comment by BalzaniEdoardo** [comment]
Hi Josh, 

Thank you for your detailed suggestions regarding the `TsGroup `class. As mentioned in the PR #263, we addressed most of your concerns. Now with `TsGroup` you can:

- filter using boolean or integer array-like objects.
- access assess columns using the `tsgroup.column_name` syntax.
- Add metadata `tsgroup["metadata"] = mydata`

We are also planning to improve the `__repr__ `for better readability.

We discussed the possibility of having `TsGroup` inherit directly from `DataFrame`. However, our experience has shown that direct use of pandas can sometimes lead to accidental manipulations of the time-axis, which is critical to avoid in `pynapple`. The current architecture of `TsGroup `helps maintain strict control over time-axis manipulations, ensuring the reliability of the data.

Cheers,
Edoardo

**Comment by gviejo** [comment]
Printing of `TsGroup` has been update in #265 so closing this issue. 
Please don't hesitate to open more issues.
