### ISSUE TITLE
IntervalSet type change on logical slicing

### ISSUE THREAD

**Issue by jolson1129** [pynapple-org/pynapple#260]
While using an interval set, logical slicing appears to transform the IntervalSet into a numpy array.

**Comment by gviejo** [comment]
Can you give an example?

**Comment by jolson1129** [comment]
I've found that a list of boolean array is okay - I had a pandas series in this case.

```
import pynapple as nap
import pandas as pd

is_simp = nap.IntervalSet(start=[0,3], end=[1,4])
bool_series = pd.Series([True, False])
print(type(is_simp[1]))
print(type(is_simp[[True, False]]))
print(type(is_simp[bool_series]))
```

Output:
<class 'pynapple.core.interval_set.IntervalSet'>
<class 'pynapple.core.interval_set.IntervalSet'>
<class 'numpy.ndarray'>

**Comment by gviejo** [comment]
Ok I see. Doesn't seem too complicated to fix.

**Comment by gviejo** [comment]
Fixed
