### ISSUE TITLE
To define the layout of electrodes when using nap.loadeeg() function

### ISSUE THREAD

**Issue by Marmotiaaa** [pynapple-org/pynapple#296]
Hi! I'm using the `load_eeg` function to read my .dat data, and I want to define my electrodes' layout  (channel map) for further analysis. Out recording system has 8 tetrodes in one group, is there any possibility for us to input this layout into this function? I guess I should use the `channel` parameter, but I'm not sure how to use it. Thanks for help!

**Comment by gviejo** [comment]
Hi yes you can pass the list of channels you want. For example `channel=0` for the first channel or `channel=[0,2]` for channels 1 and 3.
