### ISSUE TITLE
Urgent Fix: kwargs

### ISSUE THREAD

**Issue by BalzaniEdoardo** [pynapple-org/pynapple#301]
There are some methods like `IntervalSet.__init__` that has unused `**kwargs`. This can result in an unwanted behavior if one, for example, misspell a keyword argument it won't be set and no error will be raised.

We should go through all the defs that includes `**kwargs` and think if we can remove any and fix the logic.

**Comment by gviejo** [comment]
+ convolve strip the column names

**Comment by gviejo** [comment]
TsGroup test for time_support if not None

**Comment by gviejo** [comment]
check kwargs list for count
