### ISSUE TITLE
TsdFrame.smooth loses column names

### ISSUE THREAD

**Issue by rly** [pynapple-org/pynapple#307]
When running smooth on a TsdFrame, the names of the columns are reset, e.g., from [100, 200] to [0, 1]. It would be nice to keep the column names. 

```python
import pynapple as nap
```
```python
tsg = nap.TsGroup({
    100: nap.Ts([0.1, 0.2, 0.3, 0.4]),
    200: nap.Ts([0.2, 0.5, 0.55, 0.8, 1.1]),
})
```
```python
tsg
```
      Index    rate
    -------  ------
        100       4
        200       5
```python
count = tsg.count(bin_size=0.05)
count
```
    Time (s)      100    200
    ----------  -----  -----
    0.125           1      0
    0.175           0      0
    0.225           1      1
    0.275           0      0
    0.325           1      0
    0.375           0      0
    0.425           1      0
    ...
    0.775           0      0
    0.825           0      1
    0.875           0      0
    0.925           0      0
    0.975           0      0
    1.025           0      0
    1.075           0      0
    dtype: int64, shape: (20, 2)
```python
type(count)
```
    pynapple.core.time_series.TsdFrame
```python
smoothed_binned = count.smooth(0.05)
smoothed_binned
```
    Time (s)          0        1
    ----------  -------  -------
    0.125       0.36961  0.01753
    0.175       0.48246  0.12952
    0.225       0.49913  0.35207
    0.275       0.49998  0.35207
    0.325       0.49998  0.12953
    0.375       0.49913  0.01842
    0.425       0.48246  0.01927
    ...
    0.775       0        0.13041
    0.825       0        0.35208
    0.875       0        0.35207
    0.925       0        0.12952
    0.975       0        0.01753
    1.025       0        0.00087
    1.075       0        2e-05
    dtype: float64, shape: (20, 2)

**Comment by gviejo** [comment]
Thanks it's fixed already in the dev branch. It should appears soon in the next version.
