### ISSUE TITLE
Computing autocorrelogram on binned data

### ISSUE THREAD

**Issue by rly** [pynapple-org/pynapple#310]
I am sure I am missing something. I see how to use Pynapple to compute an autocorrelogram on spike times (TsGroup). But what if I have already binned the data? Is there a convenient way to compute an autocorrelogram on a binned TsdFrame using Pynapple?

**Comment by gviejo** [comment]
There is no such thing for autocorrelating time series right now. One way right now is to use the function convolve. You can do `tsd.convolve(tsd)` but the time index will not match anymore.

**Comment by rly** [comment]
OK, thanks. I ended up using [scipy.signal.correlate](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.correlate.html) on each column. Numpy.correlate would work too I think.
