### ISSUE TITLE
Handle case where occupancy values are zero.

### ISSUE THREAD

**Issue by ovalerio** [pynapple-org/pynapple#311]
Hello Pynapple Dev Team,

Thanks for creating pynapple. I found it very refreshing.  :+1: 

I'm following one of your tutorials to generate a 2d tuning curve.  That function is giving a warning about invalid value for division in the variable occupancy.

https://github.com/pynapple-org/pynapple/blob/399d52c987851754b3f34a1c3b98720dc40682c2/pynapple/process/tuning_curves.py#L223C1-L223C14

These are the values that I am using to call the function:
```
nap.compute_2d_tuning_curves(group, features, 20);

## DEBUG ##
print(group)
print(features)
nb_bins = 20
```
The output is then:
```
/home/jovyan/envs/pynapple/lib/python3.8/site-packages/pynapple/process/tuning_curves.py:223: RuntimeWarning: invalid value encountered in divide
  count = count / occupancy

  Index     rate  unit_name    histology    hemisphere      depth
-------  -------  -----------  -----------  ------------  -------
      0  2.93217  t1c1         MEC LII                     0.0024
      1  1.50193  t2c1         MEC LII                     0.0024
      2  2.57878  t2c3         MEC LII                     0.0024
      3  1.13186  t3c1         MEC LII                     0.0024
      4  1.29356  t3c2         MEC LII                     0.0024
      5  1.35857  t3c3         MEC LII                     0.0024
      6  2.8855   t3c4         MEC LII                     0.0024
      7  1.46525  t4c1         MEC LII                     0.0024

Time (s)           x         y
----------  --------  --------
0.0         -0.44279  17.1039
0.02        -0.44279  17.1039
0.04         1.26778  16.8596
0.06         1.26778  16.8596
0.08        -0.19843  17.1039
0.1         -0.19843  17.1039
0.12         1.02341  18.5701
...
599.86       2.97836   4.39679
599.88       2.97836   4.39679
599.9        2.24526   4.88552
599.92       2.24526   4.88552
599.94       2.00089   6.84047
599.96       2.00089   6.84047
599.98       0.77905   4.64115
dtype: float64, shape: (30000, 2)
  ```
Thank you,
~
Omar

**Comment by gviejo** [comment]
Hi Omar. It's a division by 0. Is it a bug report or a feature request?

**Comment by ovalerio** [comment]
Hi Guillaume, :) 

I don't know if there is a problem due to the data itself. Probably yes.

I used a dataset that I didn't acquire myself. 

And also, the warning is shown but it doesn't impact the visualisation.

**Comment by gviejo** [comment]
Hi Omar,
The idea is that having NaNs indicates the bins that the animal haven't visited. It is then easy to replace them with 0 or any other values. 
If there is no bug reported, I will close this issue.
