### ISSUE TITLE
metadata for `TsdGroup` and `TsdFrame`

### ISSUE THREAD

**Issue by clewis7** [pynapple-org/pynapple#321]
@gviejo @BalzaniEdoardo Just wanted to outline the discussion we had today:

Goal: Allow metadata to be associated with the index of `TsGroup` and the columns of `TsdFrame` so that we can color by or sort by things like preferred head direction, recording channels, etc.

 I think the general consensus is that we devise some type of `Metadata` class that can be optionally given to a `pynapple` object.  I think one thing we are still unclear on is if we should force users to fixed metadata attributes (e.g. groups or order) or not.

**Comment by gviejo** [comment]
This issue is being drafted in #343

**Comment by gviejo** [comment]
#343 has been merged. Closing this.
