### ISSUE TITLE
Loading memory map of pynapple objects (.npz)

### ISSUE THREAD

**Issue by yfujis** [pynapple-org/pynapple#327]
Hi,

Thank you for the amazing package!
I was wondering if there is a way to load the memory map but not the entire file of a pynapple object. Any guidance would be appreciated.

Thanks!

**Comment by gviejo** [comment]
Hi Yuki, 
Unfortunately we found out recently memory map doesn't work with npz as for now. See https://github.com/numpy/numpy/pull/23823.

When numpy is updated, we can provide the feature.

Best 

Guillaume

**Comment by yfujis** [comment]
Hi Guillaume,

Thank you for the reply and information!

Yuki
