### ISSUE TITLE
Remove warning for panda DataFrame loading from `nwb`

### ISSUE THREAD

**Issue by vigji** [pynapple-org/pynapple#346]
Currently, when a table with metadata is loaded from a `nwb` file it converts automatically to a data frame if metadata columns are detected; however, a warning is raised (https://github.com/pynapple-org/pynapple/blob/82df628c3d48e32ec2a3713f7e5c99e286dd2ea1/pynapple/io/interface_nwb.py#L124)

The behavior makes a lot of sense to me, and since it is documented in the loading class I do not think that is should raise a warning. What do you think?

**Comment by gviejo** [comment]
This might be solved by #343. IntervalSet will have a metadata attribute and so the full metadata of the NWB could be potentially loaded in a single IntervalSet.

**Comment by gviejo** [comment]
#343 has been merged. Closing this.
