### ISSUE TITLE
Cannot index `IntervalSet` by indexing a single row and all columns (e.g. `ep[1,:]`)

### ISSUE THREAD

**Issue by sjvenditto** [pynapple-org/pynapple#350]
Trying to index a single row and all columns of an interval set produces the error:
```
>>> ep[1,:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/svenditto/GitHub/pynapple/pynapple/core/interval_set.py", line 248, in __getitem__
    return IntervalSet(start=output[:, 0], end=output[:, 1])
                             ~~~~~~^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by sjvenditto** [comment]
I can address this in #343 since I'm already updating indexing into `IntervalSet` to be compatible with metadata

**Comment by gviejo** [comment]
With this syntax would you expect an IntervalSet or a np.ndarray? I think `ep[1]` works already and returns an IntervalSet. So doing `ep[1,:]` seems a little odd.
