### ISSUE TITLE
index after .count of TsGroup

### ISSUE THREAD

**Issue by samdeoxys1** [pynapple-org/pynapple#356]
After upgrading to 0.7.0, some old ways of indexing won't work. 

For instance, given a TsGroup, where neurons have indices, I can access the Ts based on the index of the neuron, eg:
<img width="523" alt="image" src="https://github.com/user-attachments/assets/7a1d6a0a-1062-47cb-bf22-aee69592135d">

However, after .count the TsGroup, I can no longer access the same neuron with the same index

<img width="893" alt="image" src="https://github.com/user-attachments/assets/c4061518-83cb-4202-b23b-ba9e5744f1f0">

This behavior is quite confusing to me. It used to not give an error.

**Comment by gviejo** [comment]
I think you are comparing very old versions of pynapple. This behavior relied on pandas. Pandas has been removed since 0.4. For backward compatibility, there is still the method .loc. You can do `spike_trains.count().loc[376]` and it should work.

Closing this issue if there is no error.
