### ISSUE TITLE
Ts Group keys

### ISSUE THREAD

**Issue by SSkromne** [pynapple-org/pynapple#89]
Ts group keys can only be integers

**Comment by qian-chu** [comment]
This is a quite old thread but I still want to share my two cents on this. IMO the major reason for restricting keys to be integers is that we would want keys to correspond to indices in metadata which is essentially a pandas dataframe. If you want to use strings to access Ts/Tsd, I suggest adding those strings as a metadata column.

**Comment by gviejo** [comment]
There is no plan of changing the tsgroup keys to anything but integers in the roadmap so I will close this issue.
