### ISSUE TITLE
Flexible loading of KS data

### ISSUE THREAD

**Issue by vigji** [pynapple-org/pynapple#97]
I am using the class to load Phy data, for spikes extracted with KS3. I am seeing that the loading is hardcoded to only take `"good"` spikes; I'm wondering if this could be changed to be flexible, giving the user the choice to also include eg `"mua"` if they want to for whatever reason.

I can see this happening in 2 ways (but I'm not familiar with the whole framework yet):
1. Passing an (optional) argument to to the `Phy` loader specifying the keys that are good to be loaded; this is straightforward but comes with the annoying layer of having to delete and regenerating the folder to switch eg from an analysis including everything to an analysis including only good spikes
2. Loading all files by default and add some internal filtering, that can be toggled during the analysis to expose only a fraction of the internally loaded spikes through the `self.spikes` attribute (eg changing it as a property).

Happy to work on this if you think might fit with the rest of the interface!

Cool work with the library! :)

**Comment by vigji** [comment]
Happy to try a PR on it! Can you just give me pointers on where in the H5File would you like to keep the info on the label so that it can be reloaded with the rest?

**Comment by gviejo** [comment]
Closing this issue as loading phy won't be part of pynapple anymore
